### ISSUE TITLE
t.results undefined

### ISSUE THREAD

**Issue by EBII** [clementpl/influx-crypto-watcher#3]
Is it necessary to be logged in binance to use your json ? 

![grafana_error](https://user-images.githubusercontent.com/4985100/81196757-bbc50c00-8fbf-11ea-886c-24be158914eb.png)

regards

**Comment by clementpl** [comment]
Hello
No need to go to binance or other exchange, grafana is just reporting the data in influxdb.
You get this error when uploading the json dashboard ?

**Comment by EBII** [comment]
loading the json is ok but when tying to see the dashboard generated by the import.

**Comment by clementpl** [comment]
Have try to delete and recreate the dashboard?
It looks like there is a problem with the variable (quote/base/exchange)
Did you create a watcher on BTC/USDT with the curl request given on the Readme?

**Comment by clementpl** [comment]
The 3 variable are requesting influxdb to get the different values (quote/base/exchange) accessible in the database maybe when there is no data in influx it gives the following error

**Comment by EBII** [comment]
yes i start the watcher, that generate id in response. 
i presume too that is data missing but there a db create and after few more install is use kapacitor to request and saw data in it i will retry later so i close

**Comment by EBII** [comment]
i close
